---
- hosts: pidb 
  gather_facts: yes 
  remote_user: ubuntu 
  become: yes
  become_method: sudo
  tasks:
    - name: add influx repo key 
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present

    - name: insert influx repo to apt_sources
      apt_repository: repo='deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'

    - name: apt cache update 
      apt: update_cache=yes
